### ISSUE TITLE
Make pr-sanitizer running in cluster

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/ike-prow-plugins#204]
We already have `pr-sanitizer` initial implementation in place. Enable it for our own repository to catch early bug if any.

**Steps to perform:**
- [x] saas-errortracking - add definition for the new service - https://github.com/openshiftio/saas-errortracking/pull/9
- [x] modify cico script to build all three plugins - #206
- [x] create an HK issue for the configmap update - https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2062
- [x] change osio-plugins.yaml - #205

**Comment by MatousJobanek** [comment]
I'm a bit confused. Why the HK issue contains all secrets and configmaps? Correct me if I'm wrong, the only thing that will be necessary to update is the `plugins.yaml` file. Secrets as well as the `config.yaml` file are already there...

**Comment by MatousJobanek** [comment]
and another thing is that the HK issue should have been created after the `plugins.yaml` update https://github.com/arquillian/ike-prow-plugins/pull/205 to contain the updated configuration

**Comment by dipak-pawar** [comment]
@MatousJobanek applied new configuration for pr-sanitizer. now it's enabled for `ike-prow-plugins` repo.

**Comment by MatousJobanek** [comment]
Awesome, good job @dipak-pawar :+1:
