### ISSUE TITLE
Work-in-progress plugin

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#29]
Simple plugin blocking PR from being merged if it's stil "Work In Progress"

#### Stories

- [x] PR status update https://github.com/arquillian/ike-prow-plugins/issues/25
- [x] Add "work-in-progress" label https://github.com/arquillian/ike-prow-plugins/issues/26
- [x] Change "WIP" status based on existing label https://github.com/arquillian/ike-prow-plugins/issues/27
- [x] Configuration https://github.com/arquillian/ike-prow-plugins/issues/28

**Comment by MatousJobanek** [comment]
I'm closing this epic as all of the related issues are done
