### ISSUE TITLE
Move from pilot phase to prod-preview

### ISSUE THREAD

**Issue by bartoszmajsak** [arquillian/ike-prow-plugins#68]
- [x] #62 Add probes to plugins 
- [x] #97 Configure CentosCI builds
- [x] #98 Create centos-based images for our plugins
- [ ] #99 Expose basic go runtime data to Zabbix
- [x] #100 Create saas repository
- [x] #101 Metrics collection
- [x] #110 Change Deployment objects to DeploymentConfigs
- [x] #116 Log GH rate limits
- [x] #129 Liveliness and readiness probes for the hook service
- [x]  #150 Create RHEL based images
- [x] #153 Change Sentry environment parameter to production
- [x] #155 Use IMAGE_TAG to comply with saasherder

**Comment by MatousJobanek** [comment]
Ike plugins have been deployed to http://ike-prow-plugins-hook.prod-preview.openshift.io/
